# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ролевая система U.R.S.A.
email: nickolay.malkov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roleplaying system URSA
baseurl: "/ursa_doc" # the subpath of your site, e.g. /blog
url: "https://darkmind.github.io" # the base hostname & protocol for your site
github_username:  darkmind

# Build settings
markdown: kramdown

include:
 - _includes
